// Products catalog for ShadeCast
// Note: Price, spec, and rating data are simulated/mock configurations for MVP validation.
export const sunglassesCatalog = [
  {
    id: "rayban-wayfarer-classic",
    brand: "Ray-Ban",
    model: "Original Wayfarer Classic",
    variant: "Black / G-15 Grey",
    image: "assets/road.jpg", // placeholder style image
    price: 163.00,
    msrp: 163.00,
    currency: "USD",
    retailers: [
      { name: "Amazon", url: "https://example.com/mock-affiliate?product=rb-wayfarer&network=amazon", affiliateNetwork: "amazon", price: 163.00 },
      { name: "Sunglass Hut", url: "https://example.com/mock-affiliate?product=rb-wayfarer&network=rakuten", affiliateNetwork: "rakuten", price: 163.00 }
    ],
    lensTint: "grey",
    vlt: 15,
    uvProtection: true,
    polarized: true,
    photochromic: false,
    mirrorCoating: false,
    rxCompatible: true,
    frameMaterial: "acetate",
    weight: "medium",
    activityTags: ["driving", "beach", "hiking", "golf", "disc golf"],
    weatherTags: ["sunny", "sunset", "overcast"],
    capabilities: ["road-color-neutrality", "casual-utility"],
    rating: 4.7,
    ratingSource: "Mock Review Index",
    shortDescription: "G-15 neutral green-grey lenses offer true color accuracy and excellent daily eye comfort.",
    lastVerified: "MOCK_DATA"
  },
  {
    id: "oakley-holbrook-prizm",
    brand: "Oakley",
    model: "Holbrook",
    variant: "Matte Black / Prizm Sapphire Polarized",
    image: "assets/road.jpg",
    price: 212.00,
    msrp: 212.00,
    currency: "USD",
    retailers: [
      { name: "Oakley Direct", url: "https://example.com/mock-affiliate?product=oakley-holbrook&network=cj", affiliateNetwork: "cj", price: 212.00 },
      { name: "REI", url: "https://example.com/mock-affiliate?product=oakley-holbrook&network=avantlink", affiliateNetwork: "avantlink", price: 209.99 }
    ],
    lensTint: "blue",
    vlt: 12,
    uvProtection: true,
    polarized: true,
    photochromic: false,
    mirrorCoating: true,
    rxCompatible: true,
    frameMaterial: "o-matter",
    weight: "light",
    activityTags: ["cycling", "running", "hiking", "beach", "golf", "disc golf"],
    weatherTags: ["sunny", "glare"],
    capabilities: ["water-glare", "foliage-contrast", "casual-utility"],
    rating: 4.8,
    ratingSource: "Mock Review Index",
    shortDescription: "High-contrast Prizm Sapphire lenses optimize detail and cut intense solar glare.",
    lastVerified: "MOCK_DATA"
  },
  {
    id: "mauijim-peahi-polarized",
    brand: "Maui Jim",
    model: "Peahi",
    variant: "Matte Black / SuperThin Bronze Polarized",
    image: "assets/road.jpg",
    price: 278.00,
    msrp: 278.00,
    currency: "USD",
    retailers: [
      { name: "Maui Jim", url: "https://example.com/mock-affiliate?product=mj-peahi&network=direct", affiliateNetwork: "direct", price: 278.00 },
      { name: "Bass Pro Shops", url: "https://example.com/mock-affiliate?product=mj-peahi&network=impact", affiliateNetwork: "impact", price: 278.00 }
    ],
    lensTint: "amber",
    vlt: 11,
    uvProtection: true,
    polarized: true,
    photochromic: false,
    mirrorCoating: false,
    rxCompatible: true,
    frameMaterial: "grilamid",
    weight: "medium",
    activityTags: ["fishing", "boating", "beach", "driving"],
    weatherTags: ["sunny", "glare"],
    capabilities: ["water-glare", "road-color-neutrality"],
    rating: 4.9,
    ratingSource: "Mock Review Index",
    shortDescription: "SuperThin Glass lenses paired with HCL Bronze tint yield excellent high-contrast water readings.",
    lastVerified: "MOCK_DATA"
  },
  {
    id: "goodr-og-polarized",
    brand: "Goodr",
    model: "The OGs",
    variant: "A Ginger's Soul / Black Polarized",
    image: "assets/road.jpg",
    price: 25.00,
    msrp: 25.00,
    currency: "USD",
    retailers: [
      { name: "Goodr Direct", url: "https://example.com/mock-affiliate?product=goodr-og&network=direct", affiliateNetwork: "direct", price: 25.00 },
      { name: "REI", url: "https://example.com/mock-affiliate?product=goodr-og&network=avantlink", affiliateNetwork: "avantlink", price: 25.00 }
    ],
    lensTint: "grey",
    vlt: 12,
    uvProtection: true,
    polarized: true,
    photochromic: false,
    mirrorCoating: false,
    rxCompatible: false,
    frameMaterial: "polymer",
    weight: "light",
    activityTags: ["running", "hiking", "disc golf", "cycling"],
    weatherTags: ["sunny", "sunset", "overcast"],
    capabilities: ["casual-utility"],
    rating: 4.5,
    ratingSource: "Mock Review Index",
    shortDescription: "No-slip, no-bounce frames with dark grey polarized lenses. High-value casual sports gear.",
    lastVerified: "MOCK_DATA"
  },
  {
    id: "smith-guidechoice-chromapop",
    brand: "Smith",
    model: "Guide's Choice",
    variant: "Matte Black / ChromaPop Glass Polarchromic Ignitor",
    image: "assets/road.jpg",
    price: 259.00,
    msrp: 259.00,
    currency: "USD",
    retailers: [
      { name: "Smith Optics", url: "https://example.com/mock-affiliate?product=smith-guide&network=direct", affiliateNetwork: "direct", price: 259.00 },
      { name: "Backcountry", url: "https://example.com/mock-affiliate?product=smith-guide&network=impact", affiliateNetwork: "impact", price: 259.00 }
    ],
    lensTint: "rose",
    vlt: 15,
    uvProtection: true,
    polarized: true,
    photochromic: true,
    mirrorCoating: false,
    rxCompatible: true,
    frameMaterial: "megol",
    weight: "medium",
    activityTags: ["fishing", "boating", "hiking", "disc golf"],
    weatherTags: ["sunny", "sunset", "overcast"],
    capabilities: ["water-glare", "foliage-contrast", "low-light-contrast"],
    rating: 4.8,
    ratingSource: "Mock Review Index",
    shortDescription: "Polarchromic Ignitor lenses automatically adjust transmission, perfect for varying forest shade.",
    lastVerified: "MOCK_DATA"
  },
  {
    id: "spyoptic-flynn-shield",
    brand: "Spy Optic",
    model: "Flynn",
    variant: "Soft Matte Black / Happy Bronze",
    image: "assets/road.jpg",
    price: 150.00,
    msrp: 150.00,
    currency: "USD",
    retailers: [
      { name: "Spy Optic", url: "https://example.com/mock-affiliate?product=spy-flynn&network=direct", affiliateNetwork: "direct", price: 150.00 }
    ],
    lensTint: "amber",
    vlt: 13,
    uvProtection: true,
    polarized: false,
    photochromic: false,
    mirrorCoating: true,
    rxCompatible: false,
    frameMaterial: "grilamid",
    weight: "heavy",
    activityTags: ["beach", "cycling"],
    weatherTags: ["sunny", "glare"],
    capabilities: ["casual-utility"],
    rating: 4.4,
    ratingSource: "Mock Review Index",
    shortDescription: "Fashion-forward shield frames using Happy Lens contrast booster to lift mood and colors.",
    lastVerified: "MOCK_DATA"
  },
  {
    id: "oakley-radar-ev-path",
    brand: "Oakley",
    model: "Radar EV Path",
    variant: "Polished White / Prizm Road",
    image: "assets/road.jpg",
    price: 212.00,
    msrp: 212.00,
    currency: "USD",
    retailers: [
      { name: "REI", url: "https://example.com/mock-affiliate?product=oakley-radar&network=avantlink", affiliateNetwork: "avantlink", price: 212.00 }
    ],
    lensTint: "rose",
    vlt: 20,
    uvProtection: true,
    polarized: false,
    photochromic: false,
    mirrorCoating: true,
    rxCompatible: false,
    frameMaterial: "o-matter",
    weight: "light",
    activityTags: ["cycling", "running"],
    weatherTags: ["sunny", "overcast", "sunset"],
    capabilities: ["road-color-neutrality", "low-light-contrast"],
    rating: 4.8,
    ratingSource: "Mock Review Index",
    shortDescription: "Non-polarized sport shield optimized for road running. Highlights subtle surface changes.",
    lastVerified: "MOCK_DATA"
  },
  {
    id: "tasc-glacier-blocks",
    brand: "Julbo",
    model: "Vermont Classic Glacier",
    variant: "Gunmetal / Alti Arc 4 Glass",
    image: "assets/road.jpg",
    price: 175.00,
    msrp: 175.00,
    currency: "USD",
    retailers: [
      { name: "Backcountry", url: "https://example.com/mock-affiliate?product=julbo-vermont&network=impact", affiliateNetwork: "impact", price: 175.00 }
    ],
    lensTint: "grey",
    vlt: 7,
    uvProtection: true,
    polarized: false,
    photochromic: false,
    mirrorCoating: true,
    rxCompatible: false,
    frameMaterial: "metal",
    weight: "heavy",
    activityTags: ["skiing", "snowboarding", "hiking"],
    weatherTags: ["glare"],
    capabilities: ["snow-contrast"],
    rating: 4.7,
    ratingSource: "Mock Review Index",
    shortDescription: "Category 4 Alti Arc mineral glass blocks 93% of visible light, ideal for high-altitude snow glare.",
    lastVerified: "MOCK_DATA"
  },
  {
    id: "rayban-justin-just",
    brand: "Ray-Ban",
    model: "Justin",
    variant: "Rubber Black / Grey Gradient",
    image: "assets/road.jpg",
    price: 140.00,
    msrp: 140.00,
    currency: "USD",
    retailers: [
      { name: "Amazon", url: "https://example.com/mock-affiliate?product=rb-justin&network=amazon", affiliateNetwork: "amazon", price: 138.00 }
    ],
    lensTint: "grey",
    vlt: 18,
    uvProtection: true,
    polarized: false,
    photochromic: false,
    mirrorCoating: false,
    rxCompatible: true,
    frameMaterial: "nylon",
    weight: "medium",
    activityTags: ["beach", "driving"],
    weatherTags: ["sunny", "sunset", "overcast"],
    capabilities: ["casual-utility"],
    rating: 4.6,
    ratingSource: "Mock Review Index",
    shortDescription: "Young, fun rectangular frame styling with soft gradient lenses for daily fashion utility.",
    lastVerified: "MOCK_DATA"
  },
  {
    id: "shady-cheap-knockoff",
    brand: "Retro Brand",
    model: "Sidewalk Cruiser",
    variant: "Black / Yellow Tint",
    image: "assets/road.jpg",
    price: 15.00,
    msrp: 15.00,
    currency: "USD",
    retailers: [
      { name: "Discount Mart", url: "https://example.com/mock-affiliate?product=cruiser&network=amazon", affiliateNetwork: "amazon", price: 15.00 }
    ],
    lensTint: "rose",
    vlt: 75,
    uvProtection: true,
    polarized: false,
    photochromic: false,
    mirrorCoating: false,
    rxCompatible: false,
    frameMaterial: "plastic",
    weight: "light",
    activityTags: ["cycling", "running", "driving"],
    weatherTags: ["overcast", "sunset"],
    capabilities: ["low-light-contrast"],
    rating: 3.9,
    ratingSource: "Mock Review Index",
    shortDescription: "Clear-yellow tint lens builds light visibility and contrast in heavy twilight/rain conditions.",
    lastVerified: "MOCK_DATA"
  },
  {
    id: "oakley-flak-jacket-polarized",
    brand: "Oakley",
    model: "Flak 2.0 XL",
    variant: "Matte Black / Prizm Golf",
    image: "assets/road.jpg",
    price: 184.00,
    msrp: 184.00,
    currency: "USD",
    retailers: [
      { name: "Oakley Direct", url: "https://example.com/mock-affiliate?product=oakley-flak&network=cj", affiliateNetwork: "cj", price: 184.00 }
    ],
    lensTint: "rose",
    vlt: 30,
    uvProtection: true,
    polarized: false,
    photochromic: false,
    mirrorCoating: false,
    rxCompatible: true,
    frameMaterial: "o-matter",
    weight: "light",
    activityTags: ["golf", "disc golf", "hiking"],
    weatherTags: ["overcast", "sunny", "sunset"],
    capabilities: ["foliage-contrast", "low-light-contrast"],
    rating: 4.8,
    ratingSource: "Mock Review Index",
    shortDescription: "Engineered specifically to map grass contours, tree shade boundaries, and golf ball trajectory.",
    lastVerified: "MOCK_DATA"
  },
  {
    id: "mauijim-hookipa-sport",
    brand: "Maui Jim",
    model: "Ho'okipa Sport",
    variant: "Matte Black / Neutral Grey Polarized",
    image: "assets/road.jpg",
    price: 199.00,
    msrp: 199.00,
    currency: "USD",
    retailers: [
      { name: "REI", url: "https://example.com/mock-affiliate?product=mj-hookipa&network=avantlink", affiliateNetwork: "avantlink", price: 199.00 }
    ],
    lensTint: "grey",
    vlt: 12,
    uvProtection: true,
    polarized: true,
    photochromic: false,
    mirrorCoating: false,
    rxCompatible: true,
    frameMaterial: "grilamid",
    weight: "light",
    activityTags: ["fishing", "boating", "beach", "golf", "disc golf", "hiking"],
    weatherTags: ["sunny", "glare"],
    capabilities: ["water-glare", "casual-utility"],
    rating: 4.9,
    ratingSource: "Mock Review Index",
    shortDescription: "Frameless high-utility active wraps featuring Maui Jim's premium color-enhancing polarized grey lens.",
    lastVerified: "MOCK_DATA"
  },
  {
    id: "goodr-run-og-mirror",
    brand: "Goodr",
    model: "OG Mirrored",
    variant: "Blueberry Glare Block / Blue Mirror",
    image: "assets/road.jpg",
    price: 25.00,
    msrp: 25.00,
    currency: "USD",
    retailers: [
      { name: "Goodr Direct", url: "https://example.com/mock-affiliate?product=goodr-mirror&network=direct", affiliateNetwork: "direct", price: 25.00 }
    ],
    lensTint: "blue",
    vlt: 11,
    uvProtection: true,
    polarized: true,
    photochromic: false,
    mirrorCoating: true,
    rxCompatible: false,
    frameMaterial: "polymer",
    weight: "light",
    activityTags: ["running", "beach", "cycling"],
    weatherTags: ["sunny", "glare"],
    capabilities: ["water-glare", "casual-utility"],
    rating: 4.6,
    ratingSource: "Mock Review Index",
    shortDescription: "Grip-coated frames paired with vibrant blue mirrored polarized lens, blocking glare under bright sun.",
    lastVerified: "MOCK_DATA"
  },
  {
    id: "smith-wildcat-shield",
    brand: "Smith",
    model: "Wildcat",
    variant: "Black / ChromaPop Red Mirror",
    image: "assets/road.jpg",
    price: 229.00,
    msrp: 229.00,
    currency: "USD",
    retailers: [
      { name: "Backcountry", url: "https://example.com/mock-affiliate?product=smith-wildcat&network=impact", affiliateNetwork: "impact", price: 229.00 }
    ],
    lensTint: "green",
    vlt: 15,
    uvProtection: true,
    polarized: false,
    photochromic: false,
    mirrorCoating: true,
    rxCompatible: false,
    frameMaterial: "tr90",
    weight: "light",
    activityTags: ["cycling", "hiking", "running"],
    weatherTags: ["sunny", "overcast"],
    capabilities: ["foliage-contrast", "casual-utility"],
    rating: 4.7,
    ratingSource: "Mock Review Index",
    shortDescription: "Hybrid sport shield combining performance coverage with highly responsive contrast goggles optics.",
    lastVerified: "MOCK_DATA"
  },
  {
    id: "spyoptic-touring-sport",
    brand: "Spy Optic",
    model: "Touring",
    variant: "Soft Matte Black / Happy Grey Green Polarized",
    image: "assets/road.jpg",
    price: 160.00,
    msrp: 160.00,
    currency: "USD",
    retailers: [
      { name: "Spy Optic", url: "https://example.com/mock-affiliate?product=spy-touring&network=direct", affiliateNetwork: "direct", price: 160.00 }
    ],
    lensTint: "green",
    vlt: 12,
    uvProtection: true,
    polarized: true,
    photochromic: false,
    mirrorCoating: false,
    rxCompatible: true,
    frameMaterial: "grilamid",
    weight: "medium",
    activityTags: ["driving", "hiking", "beach"],
    weatherTags: ["sunny", "glare"],
    capabilities: ["road-color-neutrality", "casual-utility"],
    rating: 4.5,
    ratingSource: "Mock Review Index",
    shortDescription: "Heavy-duty wrap frames using Happy Lens polarization to boost contrast and block UV.",
    lastVerified: "MOCK_DATA"
  }
];
